### ISSUE TITLE
Full Screen ?

### ISSUE THREAD

**Issue by badplay** [sazncode/BingRewards#29]
It have to be full screen? is there a way to use in headless silent mode? or in smaller size of browser?

alsow how to change it for other country

**Comment by sazncode** [comment]
Hello,

I've just pushed a commit to the main.py which will allow you to run the script in headless mode. Just add an .env variable `HEADLESS` to your .env, set it to true, and restart the bot.

For the second question, if you are referring to changing the currency the bot displays, if you have an Euro currency in your country, you can simply assign the value of "euro" or "€" to the `CURRENCY` .env variable. Otherwise, note that all active developers of this repository are based within the United States and therefore will be unable to guarantee functionality for every country within the Bing Rewards international community. 

We hope to add more support once the repo gains popularity internationally among developers.
Thanks for your interest in the bot.

**Comment by badplay** [comment]
thanks. is there a way to use words from other country ? some bing bots can do and use the geotag like DE for German and use the Bing top Search results for search
